version: '3.8'

services:
  pago-nube-scrapper:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DEBUG_MODE=false
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm  # Compartir memoria para mejor rendimiento de Chrome
    security_opt:
      - seccomp:unconfined  # Necesario para Chrome en algunos sistemas
    cap_add:
      - SYS_ADMIN  # Necesario para Chrome sandbox
    networks:
      - scrapper-network

networks:
  scrapper-network:
    driver: bridge 