[phases.setup]
# paquetes auto-detectados ("...") + todas las libs de Chromium/Puppeteer en Nix
nixPkgs = [
  "...",
  "chromium",
  "alsaLib",
  "atk",
  "atk_bridge",
  "cups",
  "gdk_pixbuf",
  "glib",
  "gtk3",
  "nspr",
  "nss",
  "pango",
  "libX11",
  "libX11_xcb",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXi",
  "libXrandr",
  "libXrender",
  "libXss",
  "libXtst",
  "xdg_utils",
  "fonts_liberation",
]

# opcional: solo si necesitas algún paquete extra vía apt
aptPkgs = [
  "..."
]
